package com.syncapplication.dtos.legacycobas;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DebtorsDTO {
    private BigDecimal recordNumber;
    private Short company;
    private Integer number;
    private String name1;
    private String name2;
    private String address;
    private String city;
    private String cityPostalCode;
    private Integer poBox;
    private String poBoxCity;
    private String poBoxPostalCode;
    private String searchName;
    private String phone;
    private String emailAddress;
    private String contactPerson;
    private String contactPhone;
    private String contactEmail;
    private String bankAccount;
    private String giroAccount;
    private Short companyCountry;
    private Short country;
    private Short companyLanguage;
    private Short language;
    private Short companySupplier;
    private Short supplierCondition;
    private Short paymentCondition;
    private Short companyRegion;
    private Short region;
    private Short customerCategory;
    private Short companySalesperson;
    private Short salesperson;
    private Short priceTable;
    private BigDecimal invoiceDiscount;
    private Short invoiceShipping;
    private Integer reserveCode1;
    private Short companyCurrency;
    private Short currency;
    private String blockade;
    private Short vat;
    private String accountOverview;
    private Short creditTerm;
    private Integer creditLimit;
    private BigDecimal creditRestriction;
    private BigDecimal outstandingBalance;
    private Integer outstandingDays;
    private Short outstandingPayment;
    private String faxNumber;
    private String quality;
    private Short companyExpedition;
    private Short forwarder;
    private String indicatorHandCard;
    private String indicatorSurplus;
    private String vatNumber;
    private String typeDebtor;
    private Short vat2;
    private Short debtorCode;
    private Short zipCode;
    private Short zipSequenceNumber;
    private String indicatorClassification;
    private String indicatorPostalCode;
    private Short zone;
    private String referenceName;
    private Short pvsTypeDebtor;
    private LocalDateTime startDate;
    private String website;
    private Short tradeCardNumber;
    private LocalDateTime tradeCardDate;
    private String exportDeclaration;
    private String district;
    private String debtorNumber;
    private String orderNumber;
    private String memo;
    private String invoiceText;
    private String transport;
    private String franking;
    private String extraPhone1;
    private String extraPhone2;
    private String extraPhone3;
    private String catalog;
    private Integer numberFrom;
    private BigDecimal creditorNumber;
    private String vatLiable;
    private String permitNumber;
    private BigDecimal destination;
    private String address2;
    private BigDecimal packagingCode;
    private BigDecimal paymentBehavior;
    private BigDecimal storage;
    private BigDecimal storage1;
    private BigDecimal storage2;
    private BigDecimal storage3;
    private BigDecimal storage4;
    private BigDecimal storage5;
    private BigDecimal storage6;
    private BigDecimal storage7;
    private BigDecimal storage8;
    private BigDecimal storage9;
    private BigDecimal storage10;
    private String bankName;
    private String postalAddress;
    private BigDecimal invoiceCondition;
    private String multivers;
    private String crmActive;
    private BigDecimal companyBundle;
    private BigDecimal bundle;
    private Byte krConnected;
    private BigDecimal intermediary1;
    private BigDecimal commission1;
    private BigDecimal intermediary2;
    private BigDecimal commission2;
    private BigDecimal defaultSeason;
    private Integer defaultOrder;
    private BigDecimal autumnSeason;
    private BigDecimal autumnOrder;
    private String chamberOfCommerceNumber;
    private String indicatorLogo;
    private String indicatorRinse;
    private Byte printerCode;
    private Short standardCategory;
    private BigDecimal krCountry;
    private String indicatorLogoPalletCard;
    private String indicatorStackCard;
    private String mailSubject;
    private Short multiverseExactSync;
}

